### ISSUE TITLE
Cannot run mapq_run_MP.py on Linux with SBGrid installed Chimera

### ISSUE THREAD

**Issue by rediaz111** [gregdp/mapq#1]
When trying to run the following command: /opt/sbgrid/x86_64-linux/chimera/chimera/bin/chimera  --nogui --silent --nostatus /data/rediaz/BGal/Maps/EMD-6840-aligned.mrc /data/rediaz/BGal/6cvm/6cvm_aligned_real_space_refined.pdb /opt/sbgrid/x86_64-linux/chimera/1.14/share/mapq/mapq_run_MP.py 24

I receive the following traceback error:
running proc: **/data/sbgrid/x86_64-linux/chimera/MacOS/chimera** --nogui --silent --nostatus /data/rediaz/BGal/6cvm/6cvm_aligned_real_space_refined.pdb /data/rediaz/BGal/Maps/EMD-6840-aligned_Q-score-mp_0.mrc /data/sbgrid/x86_64-linux/chimera/1.14/share/mapq/mapqp.py 
Error while processing /opt/sbgrid/x86_64-linux/chimera/1.14/share/mapq/mapq_run_MP.py:
OSError: [Errno 2] No such file or directory
  File "/data/sbgrid/x86_64-linux/chimera/1.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
See reply log for Python traceback.
Error while processing 24:
ValueError: Unknown model type
  File "/data/sbgrid/x86_64-linux/chimera/1.14/share/chimera/__init__.py", line 1916, in open
    raise ValueError, "Unknown model type"

I am able to run mapq_run.py, but not mapq_run_MP.

The path for Chimera installed by SBGrid on our Linux machine is /data/sbgrid/x86_64-linux/chimera/1.14/bin/chimera

If you could provide insight into how to solve this issue, that'd be greatly appreciated!

**Comment by gregdp** [comment]
Thanks for reporting this. 

Could you try with the new method to run from command line described in /documentation/QScores_CommandLine_v1_5.pdf. 

If you get the same error, could you also look in the folder where the map is, and paste the contents of any of the files that have _err.log extensions - these are intermediary files which will unf. not get cleaned up if the process fails, but may give some clues what's going on.

Thanks agin.

**Comment by rediaz111** [comment]
Hi Greg,
When I ran using mapq_cmd.py, it was not able to detect [path to chimera] as a path in the following command:
`python mapq_cmd.py /opt/sbgrid/x86_64-linux/chimera/1.14/bin/chimera /data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc /data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb np=36`

```
Error: 
mapq_cmd.py  -> this script
/opt/sbgrid/x86_64-linux/chimera/1.14/bin/chimera  -> map or model
/data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc  -> map or model
/data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb  -> map or model
np=36  -> number of processes: 36

 - Please specify path to Chimera. If specified, the script may not have found a valid path.
```

When I modify the chimeraPath in the script to "/opt/sbgrid/x86_64-linux/chimera/1.14/bin/chimera" and run the following command,
`python mapq_cmd.py /data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc /data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb np=36
`

I receive this output -
```
mapq_cmd.py  -> this script
/data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc  -> map or model
/data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb  -> map or model
np=36  -> number of processes: 36


Creating Chimera script in /home/robbie/Documents/mapq/mapq_chimera/mapqScript.py

Running:
 : /opt/sbgrid/x86_64-linux/chimera/1.14/bin/chimera --nogui --silent --nostatus /data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc /data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb /home/robbie/Documents/mapq/mapq_chimera/mapqScript.py

Calc Q scores:
 - chimera path :  /opt/sbgrid/x86_64-linux/chimera/1.14/bin/chimera
 - num processors:  36
 - volume: run_class001_1_2_3D_2.2.mrc

Model 1/1: 6e9d_real_space_refined.pdb
 - setting bbAts in 6e9d_real_space_refined.pdb
 - search tree: 257700/489900 ats
Q Scores - p - 36
 - map: run_class001_1_2_3D_2.2.mrc
 - mol: 6e9d_real_space_refined.pdb, chain: _all_
 - sigma: 0.60
 - mind: -0.006, maxd: 0.011
 - setting bbAts in 6e9d_real_space_refined.pdb
 - atoms to do: 257700
cmd: /data/sbgrid/x86_64-linux/chimera/1.14/share/__main__.py --nogui --silent --nostatus /data/rediaz/AAV/Maps/run_RED_2.2/run_class001_1_2_3D_2.2.mrc /data/rediaz/AAV/6e9d/6e9d_real_space_refined.pdb /home/robbie/Documents/mapq/mapq_chimera/mapqScript.py 
/data/sbgrid/x86_64-linux/chimera/1.14 share
/data/sbgrid/x86_64-linux/chimera/1.14 1.14
 **-- on mac
 -- path to Chimera: /data/sbgrid/x86_64-linux/chimera/MacOS/chimera**
Working dir: /data/sbgrid/x86_64-linux/chimera/1.14/share
 -- path to mapQ script: /data/sbgrid/x86_64-linux/chimera/1.14/share/mapq/mapqp.py
 - 1/36, 226-606
**Error while processing /home/robbie/Documents/mapq/mapq_chimera/mapqScript.py:
ValueError: zero-size array to reduction operation minimum which has no identity

  File "/data/sbgrid/x86_64-linux/chimera/1.14/lib/python2.7/site-packages/numpy/core/_methods.py", line 14, in _amin
    out=out, keepdims=keepdims)**

See reply log for Python traceback.
```


There are no _err.log files in the directory where the maps are.

**Comment by gregdp** [comment]
Hi Roberto,

I guess the [path to chimera] part is meant to be where Chimera is installed, so in your case just:
/opt/sbgrid/x86_64-linux/chimera/1.14
rather than to the actual binary:
/opt/sbgrid/x86_64-linux/chimera/chimera/bin/chimera
But I like your fix to put it in the script itself!

About the second problem, I was able to replicate, this happens when some big portion of the atoms are well outside the map*. I fixed the code to handle this in the new version 1.5.2 - could you try?

* This can happen if, say:
1. the model is not (yet) fitted to the map
2. the model is fitted but in software that interprets the origin of the map in a different way than Chimera (I think Coot and Phenix in particular). Thinking ahead, I don't know if there could be a way to deal with this automatically...

Thanks!
Greg

**Comment by gregdp** [comment]
I should mention, if #2 is the issue, I can try to see if I can get Chimera to interpret the origin the other way, and it could be specified via a command-line parameter...

**Comment by rediaz111** [comment]
I was able to run the script with multiple processors using v1.5.2 and [path_to_chimera] pointing to the path instead of the binary. Thanks for your help!
