### ISSUE TITLE
Cannot get results in txt file when running mapq_cmd.py on the command line

### ISSUE THREAD

**Issue by rediaz111** [gregdp/mapq#3]
When I run MapQ using the Chimera plugin, it generates a results.txt file. [chimera_output.txt](https://github.com/gregdp/mapq/files/4571437/chimera_output.txt)

However, when I use mapq_cmd.py within the command line, no results.txt file is generated. I was able to save the command line output to a file using ```python mapq_cmd.py [path_to_chimera] [map_file] [model_file] > output.txt``` but this does not contain the same depth of information as what is produced from the Chimera plugin.
[commandline_output.txt](https://github.com/gregdp/mapq/files/4571438/commandline_output.txt)

Could you add functionality to mapq_cmd.py to write out the same type of results.txt file as the plugin? Thanks for your time!

**Comment by gregdp** [comment]
good idea... working on it

**Comment by gregdp** [comment]
Added this to v1.5.3. The per-chain and per-residue Q-scores are now output to a file after each run, including with command line. The file name is something like [path to pdb file]--Q--[map name]_All.txt'. Note there is also a new 'res' parameter for the command line, e.g. res=2.0; this is used only so Q-scores can be compared to the expected Q-scores at this resolution. Hope this works!

**Comment by rediaz111** [comment]
It works perfectly, thanks!
