### ISSUE TITLE
AttributeError when processing DNA residues

### ISSUE THREAD

**Issue by pameyer** [gregdp/mapq#4]
Models with "DT" residue names trigger `AttributeError: '_molecule.Atom' object has no attribute 'isBB'` from `CalcResQ`.

This appears to be due to `SetBBAts` checking for nucleic acids, treating all nucleic acids as RNA for bb/sc attribute determination, and not having a code path for "DT" ("DA","DC", and "DG" have a path from the `nucleic3to1` check).

**Comment by gregdp** [comment]
Thanks for reporting this. I checked in Chimera and "DT" seems to be in nucleic3to1:

>>> from chimera.resCode import nucleic3to1
>>> nucleic3to1
{'A': 'A', '+C': 'C', '+A': 'A', '+G': 'G', 'THY': 'T', 'G': 'G', 'CYT': 'C', 'DC': 'C', 'DG': 'G', 'GUA': 'G', 'C': 'C', 'DA': 'A', 'ADE': 'A', 'U': 'U', 'T': 'T', '+U': 'U', '+T': 'T', 'DT': 'T', 'URA': 'U'}

I'm trying to find out why the isBB may not be set - could you send any more info on how this was triggered? Was it from the UI?

**Comment by gregdp** [comment]
I tried setting a check for isBB, and set it otherwise, it's in v. 1.6.3 - please check if this fixes the issue?

**Comment by pameyer** [comment]
This can be triggered from the chimera (1.14) UI.  It looks to me like it's coming from the `elif r.isNA` block in SetBBAts (8794:8807 in mapq.py), where it's checking G,C,A,U - the default "else" in that block.  I'm not sure why the "else/break" is getting triggered for DT - it was looking it it should, but that was my best guess.

**Comment by pameyer** [comment]
Sorry about the crossing messages - I'll check 1.6.3 (is there a tag or commit hash for that)?

Thanks for the quick replies :)

**Comment by gregdp** [comment]
My pleasure; I enjoy working on this to fix the bugs!
So, I see what you mean about those cases, I have to add one more else there for DNA. But the isBB should already be set by that point, the side chain atoms will likely not be right though so that could lead to another issue.
So, the issue in this case is more likely that SetBBAtoms was not called for the model in the first place - I found this may happen if selecting atoms but not selecting the model in the dialog for example.

Btw. I'm not familiar with tags or commit hashes - trying to look it up, but what are they used for?

**Comment by pameyer** [comment]
1.6.3 (I realized you meant the zip file after I'd asked) does fix it (after fixing qscores.py:1895 `if not hasattr ( 'isBB' )` to ` if not hasattr ( at, 'isBB' ) `).  I did some debugging with PDB 6x0l - other DNA residues seemed ok (but there's a chance I wasn't using the most recent version of mapq for that testing, so I may be going down the wrong path).


I'd been referring to git tags (https://git-scm.com/book/en/v2/Git-Basics-Tagging) or commit hashes (e725f504b3af4d53adb620333cd969113bd0c757 for your most recent) - different people mean different things by "release", and I was going down the wrong path by looking at https://github.com/gregdp/mapq/releases.

**Comment by gregdp** [comment]
glad to hear it does fix it; i will check also with 6x0l to see if there are any other issues, i had not looked at any DNA models before actually... this is all still a bit new

**Comment by pameyer** [comment]
Thanks again!

**Comment by gregdp** [comment]
thank you too; good catch on the other missing arg... fixing it in the release now, and will check some more with 6x0l

**Comment by gregdp** [comment]
also, I see what you mean now about releases - good idea to use these actually
